description = "Display detailed information about an application (dumpsys)."
prompt = """
Display detailed information about an application (dumpsys).
Enter the following parameters: <package_name param name>.
Example execution: adb shell dumpsys package <package_name>.
"""
