description = "Change the permissions of a file or directory."
prompt = """
Change the permissions of a file or directory.
Enter the following parameters: <permissions param name>, <path param name>.
Example execution: adb shell chmod 777 /sdcard/file.txt.
"""
