description = "Change the owner of a file or directory."
prompt = """
Change the owner of a file or directory.
Enter the following parameters: <owner:group param name>, <path param name>.
Example execution: adb shell chown root:root /sdcard/file.txt.
"""
