description = "Clear the data of an application."
prompt = """
Clear the data of an application.
Enter the following parameters: <package_name param name>.
Example execution: adb shell pm clear <package_name>.
"""
