description = "Disable an application."
prompt = """
Disable an application.
Enter the following parameters: <package_name param name>.
Example execution: adb shell pm disable-user <package_name>.
"""
