description = "Display system diagnostic information."
prompt = """
Display system diagnostic information.
Enter the following parameters: <service_name (optional) param name>.
Example execution: adb shell dumpsys activity.
"""
