description = "Long press a position on the screen."
prompt = """
Long press a position on the screen.
Enter the following parameters: <x param name>, <y param name>, <time (ms) param name>.
Example execution: adb shell input swipe 500 1000 500 1000 1500.
"""
