description = "Swipe on the screen."
prompt = """
Swipe on the screen.
Enter the following parameters: <x1 param name>, <y1 param name>, <x2 param name>, <y2 param name>, <time (ms) (optional) param name>.
Example execution: adb shell input swipe 100 500 900 500 200.
"""
