description = "Set the application as debuggable."
prompt = """
Set the application as debuggable.
Enter the following parameters: <package_name param name>.
Example execution: adb shell am set-debug-app -w <package_name>.
"""
