description = "Display or set the screen DPI density."
prompt = """
Display or set the screen DPI density.
Enter the following parameters: <density (dpi) (optional) param name>.
Example execution: adb shell wm density 480.
"""
