description = "Display or set the screen size."
prompt = """
Display or set the screen size.
Enter the following parameters: <width x height (optional) param name>.
Example execution: adb shell wm size 1080x1920.
"""
